---
title: "Homework 07"
author: "Caitlin Jeffrey"
date: "March 17, 2021"
output: html_document
---

# Homework 7

```{r}
library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
library(broman)

# read in my somatic cell count data (log2, neg and zeroes removed)
z <- read.table("scc.csv",header=TRUE,sep=",", stringsAsFactors=FALSE) # 2332 observations 
str(z) # variable is numeric
summary(z)
```

```{r}
# quick and dirty, a truncated normal distribution to work on the solution set - commented out so z becomes my scc data

# z <- rnorm(n=3000,mean=0.2)
# z <- data.frame(1:3000,z)
# names(z) <- list("ID","myVar")
# z <- z[z$myVar>0,]
# str(z)
# summary(z$myVar)
```

```{r}
# Plot a histogram of the data (rescaling the y axis of the histogram from counts to density, so that the area under the histogram equals 1.0)

p1 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="#8f509d",size=0.2) 
print(p1)
```

```{r}
# kernel density plot of the data (empirical curve that is fitted to the data, smooths out the shape of the histogram)

p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```

```{r}
#  fit a normal distribution to your data, get maximum likelihood estimators of the two parameters of the normal, the mean and the variance

normPars <- fitdistr(z$myVar,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute
```


```{r}
# generate probability density for the NORMAL distribution. First get maximum likelihood parameters for a normal distribution fitted to these data by calling fitdistr, then pass those parameters (meanML and sdML to stat_function

meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$myVar),len=length(z$myVar))

stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$myVar), args = list(mean = meanML, sd = sdML))
 p1 + stat

```

```{r}
# Plot exponential probability density (use same template, add in the curve for the exponential)

expoPars <- fitdistr(z$myVar,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$myVar), args = list(rate=rateML))
 p1 + stat + stat2
```

```{r}
# Plot uniform probability density (don’t need to use fitdistr because the maximum likelihood estimators of the two parameters are just the minimum and the maximum of the data)
  
stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$myVar), args = list(min=min(z$myVar), max=max(z$myVar)))
 p1 + stat + stat2 + stat3
```

```{r}
# Plot gamma probability density

gammaPars <- fitdistr(z$myVar,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$myVar), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4

```

```{r}
# Plot beta probability density (has to be shown in its own plot because the raw data must be rescaled so they are between 0 and 1, and then they can be compared to the beta)

pSpecial <- ggplot(data=z, aes(x=myVar/(max(myVar + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$myVar/max(z$myVar + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$myVar), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial

```


## Best fitting distribution looks like it was the gamma

```{r}
# maximum likelihood parameters from gamma distribution of my data
print(shapeML) # 1.286966
print(rateML) # 0.4714863 (scale = 1/rate)

# make a new simulated data set with above MLP's

new_gamma <- rgamma(n=length(z$myVar), shape=shapeML, scale=(1/rateML))
new_gamma <- as.data.frame(new_gamma)
names(new_gamma)[names(new_gamma) == "new_gamma"] <- "myVar"
summary(new_gamma$myVar)

gammaPars1 <- fitdistr(new_gamma$myVar,"gamma")
shapeML1 <- gammaPars1$estimate["shape"]
rateML1 <- gammaPars1$estimate["rate"]

xval1 <- seq(0,max(new_gamma$myVar),len=length(new_gamma$myVar))

p1a <- ggplot(data=new_gamma, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2)


new_gamma_plot <- stat_function(aes(x = xval1, y = ..y..), fun = dgamma,  colour="brown", n = length(new_gamma$myVar), args = list(shape=shapeML1, rate=rateML1))

print(p1a + new_gamma_plot + geom_density(linetype="dotted",size=0.75))
print(p1)

# the two histograms look pretty similar; if the scale on the x-axis of the modeled data histogram was the same as the actual data, they would look very much alike
```













