---
title: "Homework 06"
author: "Caitlin Jeffrey"
date: "March 10, 2021"
output: html_document
---
# Question 1

```{r}
n_dims <- sample(3:10,1) # 3 first time I did it
my_vec <- (1:(n_dims^2)) # 1-9 (from 3)
shuffle_my_vec <-sample(my_vec)
m <- matrix(data=shuffle_my_vec, nrow=n_dims)
print(m)
```

```{r}
trans_m <- t(m) # transpose m
print(trans_m)
```

```{r}
# from when n_dims was 3
first_sum <-sum(trans_m[1,]) # 19
first_mean <-mean(trans_m[1,]) # 6.333
last_sum <-sum(trans_m[3,]) # 18
last_mean <-mean(trans_m[3,]) # 6
```

```{r}
eigen(trans_m) 
typeof(eigen(trans_m)$values) # sooo complex!
```

# Question 2

```{r}
my_matrix <- matrix(data=runif(16), nrow=4)

hundred_values <- sample(1:200,100)
my_logical <-hundred_values < 100

my_letters <- sample(letters)

my_list <- list(my_matrix, my_logical, my_letters)

new_list <- list(my_matrix[2,2], my_logical[2], my_letters[2])

typeof(new_list[[1]]) # double
typeof(new_list[[2]]) # logical
typeof(new_list[[3]]) # character

single_vec <- c(new_list[[1]],new_list[[2]], new_list[[3]])
typeof(single_vec[[1]]) # character
```

# Question 3

```{r}
my_df <- data.frame(my_unis=(sample(0:10,26, replace=T)), my_letters=(LETTERS))

my_df[sample(1:26,4),1] <- NA

which(is.na(my_df)) # which rows contain NA

my_df <- my_df[order(my_df$my_letters),] # sort alphabetically for my_letters

mean(my_df$my_unis, na.rm=T) # 4.27 for original list generated
```



